name = "chromium-update-server"
main = "src/index.ts"
compatibility_date = "2023-10-16"

# Use environment variables for account_id
account_id = "c6452865d04ed5bd485084005c60cb02"

# Bind to the D1 database
[[d1_databases]]
binding = "DB"
database_name = "chromium_updates"
database_id = "${CLOUDFLARE_D1_ID}"

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "${CLOUDFLARE_KV_ID}"
preview_id = "${CLOUDFLARE_KV_ID}"
