name = "chromium-update-worker"
main = "src/index.ts"
compatibility_date = "2023-10-16"

# Use environment variables for account_id
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Bind to the D1 database
[[d1_databases]]
binding = "DB"
database_name = "chromium_updates"
database_id = "${CLOUDFLARE_D1_ID}"

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "${CLOUDFLARE_KV_ID}"