name = "browser-update-server"
main = "src/index.ts"
compatibility_date = "2023-10-16"

account_id = "c6452865d04ed5bd485084005c60cb02"

[[d1_databases]]
binding = "DB"
database_name = "chromium_updates"
database_id = "20dd4a07-91c3-4124-a06f-554bc5b0f9b6"

[[kv_namespaces]]
binding = "CACHE"
id = "82c269886358409ea6ea6f72b7281e6c"
preview_id = "931b43d30884411288f1bbf459ddd0c9"

[[kv_namespaces]]
binding = "SESSION_STORE"
id = "82c269886358409ea6ea6f72b7281e6c"
preview_id = "931b43d30884411288f1bbf459ddd0c9"

# Environment variables
# These should be set in the Cloudflare dashboard for production
[vars]
# GitHub OAuth credentials
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""

# Security settings
ENCRYPTION_KEY = ""
SESSION_SECRET = ""
ALLOWED_ADMIN_USERS = "admin1,admin2"

# CORS configuration
ALLOWED_ORIGINS = "http://localhost:3000,http://localhost:5173"

# Rate limiting
AUTH_RATE_LIMIT = "10"  # 10 requests per minute for auth endpoints
API_RATE_LIMIT = "100"  # 100 requests per minute for API endpoints

# Security headers for production
[env.production.security_headers]
Content-Security-Policy = "default-src 'self'; script-src 'self'; connect-src 'self' https://api.github.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; form-action 'self';"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cron triggers for maintenance tasks
[triggers]
crons = ["0 0 * * *"] # Run daily at midnight UTC
