name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Cloudflare Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Create Cloudflare Pages project if it doesn't exist
        run: |
          PROJECT_EXISTS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/chromium-update-server" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" | jq -r '.success')
          if [ "$PROJECT_EXISTS" != "true" ]; then
            echo "Creating Cloudflare Pages project..."
            curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects" \
              -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data '{"name":"chromium-update-server","production_branch":"main"}'
          else
            echo "Cloudflare Pages project already exists."
          fi

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: chromium-update-server
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  deploy-worker:
    runs-on: ubuntu-latest
    name: Deploy Worker to Cloudflare
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./worker
        run: npm install

      - name: Create D1 database if it doesn't exist
        run: |
          npm install -g wrangler
          cd ./worker
          DB_EXISTS=$(wrangler d1 list --json | jq -r '.[] | select(.name=="chromium_updates") | .name')
          if [ "$DB_EXISTS" != "chromium_updates" ]; then
            echo "Creating D1 database..."
            wrangler d1 create chromium_updates
            wrangler d1 execute chromium_updates --file=../fine/migrations/20250414011058_create_initial_schema.sql
          else
            echo "D1 database already exists."
          fi

      - name: Create KV namespace if it doesn't exist
        run: |
          npm install -g wrangler
          cd ./worker
          KV_EXISTS=$(wrangler kv namespace list | jq -r '.[] | select(.title=="chromium_updates_cache") | .title')
          if [ "$KV_EXISTS" != "chromium_updates_cache" ]; then
            echo "Creating KV namespace..."
            wrangler kv namespace create chromium_updates_cache
          else
            echo "KV namespace already exists."
          fi

      - name: Deploy Worker
        working-directory: ./worker
        env:
          GITHUB_CLIENT_ID: ${{ secrets.CF_GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.CF_GITHUB_CLIENT_SECRET }}
          GITHUB_OWNER: ${{ secrets.CF_GITHUB_OWNER }}
          GITHUB_REPO: ${{ secrets.CF_GITHUB_REPO }}
          GITHUB_TOKEN: ${{ secrets.CF_GITHUB_TOKEN }}
        run: npx wrangler deploy
