name: Run Tests

on:
  # Run on all pull requests
  pull_request:
    types: [opened, synchronize, reopened]
  
  # Run on push to any branch
  push:
    branches-ignore:
      - main
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Generate test coverage report
        run: npm run test:coverage
      
      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
      
      - name: Comment PR with coverage report
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-coverage
          message: |
            ## Test Coverage Report
            
            ```
            $(cat coverage/lcov-report/index.html | grep -A 5 "<div class='fl pad1y space-right2'>" | sed 's/<[^>]*>//g' | sed 's/^[ \t]*//' | grep -v "^$")
            ```
            
            [View detailed coverage report](https://htmlpreview.github.io/?https://github.com/${{ github.repository }}/blob/${{ github.sha }}/coverage/lcov-report/index.html)
